<template >

  <div class="animation-container dark:text-white"></div>
</template>

<script>
export default {
  data() {
    return {
      chars: [
        "The Shawshank Redemption",
       "The Godfather", 
  "The Dark Knight", 
  "The Godfather Part II", 
  "12 Angry Men", 
  "Schindler's List", 
  // "The Lord of the Rings: The Return of the King", 
  "Pulp Fiction", 
  // "The Lord of the Rings: The Fellowship of the Ring", 
  "The Good", "the Bad and the Ugly", 
  "Forrest Gump", 
  "Fight Club", 
  "Inception", 
  // "The Lord of the Rings: The Two Towers", 
  // "Star Wars: Episode V - The Empire Strikes Back", 
  "The Matrix", 
  "Goodfellas", 
  // "One Flew Over the Cuckoo's Nest", 
  "Se7en", 
  "Seven Samurai", 
  "It's a Wonderful Life", 
  "The Silence of the Lambs", 
  "City of God", 
  "Saving Private Ryan", 
  "Life Is Beautiful", 
  "The Green Mile", 
  "Interstellar", 
  "Star Wars", 
  "Terminator 2: Judgment Day", 
  "Back to the Future", 
  "Spirited Away", 
  "Psycho", 
  "The Pianist", 
  "Léon: The Professional", 
  "Parasite", 
  "The Lion King", 
  "Gladiator", 
  "American History X", 
  "The Departed", 
  "The Usual Suspects", 
  "The Prestige", 
  "Casablanca", 
  "Whiplash", 
  "The Intouchables", 
  "Harakiri", 
  "Modern Times", 
  "Grave of the Fireflies", 
  // "Once Upon a Time in the West", 
  "Top Gun: Maverick", 
  "Rear Window", 
  "Alien", 
  "City Lights", 
  "Cinema Paradiso", 
  "Memento", 
  "Apocalypse Now", 
  // "Indiana Jones and the Raiders of the Lost Ark", 
  "Django Unchained", 
  "WALL·E", 
  "The Lives of Others", 
  "Sunset Blvd.", 
  "Paths of Glory", 
  "The Shining", 
  "The Great Dictator", 
  "Witness for the Prosecution", 
  "Avengers: Infinity War", 
  "Aliens", 
  "American Beauty", 
  // "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", 
  "Spider-Man: Into the Spider-Verse", 
  "The Dark Knight Rises", 
  "Oldboy", 
  "Joker", 
  "Amadeus", 
  "Braveheart", 
  "Toy Story", 
  "Coco", 
  "The Boat", 
  "Inglourious Basterds", 
  "Princess Mononoke", 
  "Avengers: Endgame", 
  "Once Upon a Time in America", 
  "Good Will Hunting", 
  "Your Name.", 
  "Requiem for a Dream", 
  "Toy Story 3", 
  "Singin' in the Rain", 
  "3 Idiots", 
  // "Star Wars: Episode VI - Return of the Jedi", 
  "High and Low", 
  "2001: A Space Odyssey", 
  // "Eternal Sunshine of the Spotless Mind", 
  "Reservoir Dogs", 
  "Capernaum", 
  "Citizen Kane", 
  "Lawrence of Arabia", 
  "The Hunt", 
  "M", 
  "North by Northwest", 
  "Vertigo", 
  "Come and See", 
  "Amélie", 
  "A Clockwork Orange", 
  "Double Indemnity", 
  "Full Metal Jacket", 
  "The Apartment", 
  "Scarface", 
  "Ikiru", 
  "The Sting", 
  "To Kill a Mockingbird", 
  "Taxi Driver", 
  "Up", 
  "Heat", 
  "L.A. Confidential", 
  "Metropolis", 
  "A Separation", 
  "Incendies", 
  "Die Hard", 
  "Snatch", 
  "Hamilton", 
  "Indiana Jones and the Last Crusade", 
  "Bicycle Thieves", 
  1917, 
  "Like Stars on Earth", 
  "Downfall", 
  "For a Few Dollars More", 
  "Batman Begins", 
  "Dangal", 
  "The Kid", 
  "Some Like It Hot", 
  "Spider-Man: No Way Home", 
  "All About Eve", 
  "The Father", 
  "Green Book", 
  "The Wolf of Wall Street", 
  "Judgment at Nuremberg", 
  "Ran", 
  "Unforgiven", 
  "Casino", 
  "Pan's Labyrinth", 
  "There Will Be Blood", 
  "The Sixth Sense", 
  "The Truman Show", 
  "A Beautiful Mind", 
  "Monty Python and the Holy Grail", 
  "Yojimbo", 
  "The Treasure of the Sierra Madre", 
  "Shutter Island", 
  "Jurassic Park", 
  "Rashomon", 
  "The Great Escape", 
  "Kill Bill: Vol. 1", 
  "No Country for Old Men", 
  "Finding Nemo", 
  "The Elephant Man", 
  "Chinatown", 
  "Raging Bull", 
  "Gone with the Wind", 
  "The Thing", 
  "V for Vendetta", 
  "Inside Out", 
  "Lock", "Stock and Two Smoking Barrels", 
  "Dial M for Murder", 
  "The Secret in Their Eyes", 
  "Howl's Moving Castle", 
  "The Bridge on the River Kwai", 
  // "Three Billboards Outside Ebbing", "Missouri", 
  "Trainspotting", 
  "Everything Everywhere All at Once", 
  "Warrior", 
  "Gran Torino", 
  "Fargo", 
  "Prisoners", 
  "My Neighbor Totoro", 
  "Million Dollar Baby", 
  "The Gold Rush", 
  "Catch Me If You Can", 
  "Blade Runner", 
  "On the Waterfront", 
  "Children of Heaven", 
  "The Third Man", 
  "Ben-Hur", 
  "Wild Strawberries", 
  "Before Sunrise", 
  "12 Years a Slave", 
  "The General", 
  "Gone Girl", 
  // "Harry Potter and the Deathly Hallows: Part 2", 
  "The Deer Hunter", 
  "In the Name of the Father", 
  "The Grand Budapest Hotel", 
  "Mr. Smith Goes to Washington", 
  "The Wages of Fear", 
  "Barry Lyndon", 
  "Sherlock Jr.", 
  "Memories of Murder", 
  "Hacksaw Ridge", 
  "Klaus", 
  "The Seventh Seal", 
  "Wild Tales", 
  "Room", 
  "Mad Max: Fury Road", 
  "The Big Lebowski", 
  "How to Train Your Dragon", 
  "Mary and Max", 
  "Monsters", "Inc.", 
  "Jaws", 
  "The Passion of Joan of Arc", 
  "Tokyo Story", 
  "Dead Poets Society", 
  "Hotel Rwanda", 
  "Rocky", 
  "Platoon", 
  "Ford v Ferrari", 
  "Pather Panchali", 
  "Stand by Me", 
  "The Terminator", 
  "Spotlight", 
  "Rush", 
  "Network", 
  "Logan", 
  "Into the Wild", 
  "The Wizard of Oz", 
  "Ratatouille", 
  "Groundhog Day", 
  "Before Sunset", 
  "The Exorcist", 
  "The Best Years of Our Lives", 
  "The Incredibles", 
  "To Be or Not to Be", 
  "The Battle of Algiers", 
  "The Grapes of Wrath", 
  "Rebecca", 
  "Hachi: A Dog's Tale", 
  "Cool Hand Luke", 
  "Amores perros", 
  // "Pirates of the Caribbean: The Curse of the Black Pearl", 
  "La Haine", 
  "The 400 Blows", 
  "Persona", 
  "My Father and My Son", 
  "It Happened One Night", 
  "Life of Brian", 
  "The Sound of Music", 
  "The Handmaiden", 
  "Dersu Uzala", 
  "Gandhi", 
  "Aladdin", 
  "Jai Bhim", 
  "The Help", 
  "Beauty and the Beast"
      ],
      container: null,
    };
  },
  mounted() {
    this.container = this.$el;
    setInterval(this.add, 100);
  },
  methods: {
    add() {
      let element = document.createElement("span");
      this.container.appendChild(element);
      this.animate(element);
    },
    animate(element) {
      let character = this.chars[Math.floor(Math.random() * this.chars.length)];
      let duration = Math.floor(Math.random() * 15) + 1;
      let offset = Math.floor(Math.random() * (50 - duration * 2)) + 3;
      let size = 6 + (15 - duration);
      element.style.cssText =
        "right:" +
        offset +
        "vw; font-size:" +
        size +
        "px;animation-duration:" +
        duration +
        "s";
      element.innerHTML = character;
      setTimeout(() => this.remove(element), duration * 1000);
    },
    remove(element) {
      element.parentNode.removeChild(element);
    },
  },
};
</script>
<style scoped>

</style>